Repository sysagnostic/website, pull requests merged in 2025-04, with the labels that each got.

#32 Fix AWS S3 blog post article image
  static/images/blog/how-its-made-cloudarch.svg
Labels: bug

#33 Change T&M pricing unit
  data/en/pricing.yml
Labels: enhancement

#37 Fix typo of S3 website blog article
  content/english/blog/s3-static-website.md
Labels: bug

#38 SEO optimization
  .github/workflows/aws-deploy.yml
  data/en/feature.yml
Labels: enhancement

#42 Update motto and style fixes
  assets/css/custom.css
  data/en/feature.yml
  data/en/portfolio.yml
  data/en/pricing.yml
  data/en/service.yml
Labels: bug, enhancement

#43 Fix badge scroll performance issue and typo
  assets/css/custom.css
  data/en/certificate.yml
  themes/meghna-hugo/assets/js/script.js
  themes/meghna-hugo/layouts/partials/certificate.html
Labels: bug

#45 Update Tamas' job title
  content/english/author/tamas-rebeli.md
  content/english/team/tamas-rebeli.md
  data/en/team.yml
Labels: bug

#46 Beautify Tamas' Mikrotik certificates in CV
  content/english/team/tamas-rebeli.md
Labels: enhancement

#51 Cost-efficient disaster recovery blog post
  content/english/blog/cost-efficient-dr.md
  static/images/blog/cost-efficient-dr-cover.jpg
  static/images/blog/cost-efficient-dr-cover.webp
  static/images/blog/cost-efficient-dr-strategies-active-active.svg
  static/images/blog/cost-efficient-dr-strategies-backup-restore.svg
  static/images/blog/cost-efficient-dr-strategies-cold-standby.svg
  static/images/blog/cost-efficient-dr-strategies-pilot-light.svg
  static/images/blog/cost-efficient-dr-strategies-warm-standby.svg
Labels: enhancement
